// @vitest-environment node
import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

const projectFile = resolve('ios/App/App.xcodeproj/project.pbxproj');
const backgroundTaskFile = resolve('ios/App/App/DownloadBackgroundTask.swift');

describe('iOS native background downloads', () => {
  it('includes native download and UniFFI Swift files in the App target sources', () => {
    const project = readFileSync(projectFile, 'utf8');

    for (const file of [
      'BypassPlugin.swift',
      'DownloadBackgroundTask.swift',
      'DownloadWorkerPlugin.swift',
      'bypass.swift',
    ]) {
      expect(project).toContain(`/* ${file} */`);
      expect(project).toContain(`/* ${file} in Sources */`);
    }
  });

  it('links the generated bypass UniFFI static library for native downloads', () => {
    const project = readFileSync(projectFile, 'utf8');

    expect(project).toContain('/* libbypass_uniffi.a */');
    expect(project).toContain('/* libbypass_uniffi.a in Frameworks */');
    expect(project).toContain('HEADER_SEARCH_PATHS');
    expect(project).toContain('SWIFT_INCLUDE_PATHS');
    expect(project).toContain('LIBRARY_SEARCH_PATHS');
    expect(project).toContain('"$(PROJECT_DIR)/App"');
    expect(project).toContain('"$(PROJECT_DIR)/App/Frameworks"');
  });

  it('uses the generated UniFFI binding in the app target instead of importing a missing bypass module', () => {
    for (const file of ['BypassPlugin.swift', 'DownloadBackgroundTask.swift']) {
      const source = readFileSync(resolve('ios/App/App', file), 'utf8');

      expect(source).not.toContain('import bypass');
      expect(source).toContain('bypassDownloadToFile');
    }
  });

  it('backs off failed background runs before rescheduling', () => {
    const source = readFileSync(backgroundTaskFile, 'utf8');

    expect(source).toContain(
      'BGTaskScheduler.shared.cancel(taskRequestWithIdentifier: Self.taskIdentifier)',
    );
    expect(source).toContain('scheduleProcessingTask(after: 5 * 60)');
    expect(source).toContain('request.earliestBeginDate = Date(timeIntervalSinceNow: delay)');
  });

  it('refreshes the manifest when background resume skips an existing page', () => {
    const source = readFileSync(backgroundTaskFile, 'utf8');

    expect(source).toContain('if isNonEmptyFile(dest) {');
    expect(source).toContain(
      'writeManifest(galleryDir: galleryDir, exts: Array(exts.prefix(i + 1)))',
    );
  });
});
