// @vitest-environment node
import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

const projectFile = resolve('ios/App/App.xcodeproj/project.pbxproj');
const backgroundTaskFile = resolve('ios/App/App/DownloadBackgroundTask.swift');
const downloadWorkerPluginFile = resolve('ios/App/App/DownloadWorkerPlugin.swift');
const appDelegateFile = resolve('ios/App/App/AppDelegate.swift');
const infoPlistFile = resolve('ios/App/App/Info.plist');

describe('iOS native background downloads', () => {
  it('includes native download and UniFFI Swift files in the App target sources', () => {
    const project = readFileSync(projectFile, 'utf8');

    for (const file of [
      'BypassPlugin.swift',
      'DownloadBackgroundTask.swift',
      'DownloadWorkerPlugin.swift',
      'bypass.swift',
    ]) {
      expect(project).toContain(`/* ${file} */`);
      expect(project).toContain(`/* ${file} in Sources */`);
    }
  });

  it('links the generated bypass UniFFI static library for native downloads', () => {
    const project = readFileSync(projectFile, 'utf8');

    expect(project).toContain('/* libbypass_uniffi.a */');
    expect(project).toContain('/* libbypass_uniffi.a in Frameworks */');
    expect(project).toContain('HEADER_SEARCH_PATHS');
    expect(project).toContain('SWIFT_INCLUDE_PATHS');
    expect(project).toContain('LIBRARY_SEARCH_PATHS');
    expect(project).toContain('"$(PROJECT_DIR)/App"');
    expect(project).toContain('"$(PROJECT_DIR)/App/Frameworks"');
  });

  it('uses the generated UniFFI binding in the app target instead of importing a missing bypass module', () => {
    for (const file of ['BypassPlugin.swift', 'DownloadBackgroundTask.swift']) {
      const source = readFileSync(resolve('ios/App/App', file), 'utf8');

      expect(source).not.toContain('import bypass');
      expect(source).toContain('bypassDownloadToFile');
    }
  });

  it('backs off failed background runs before rescheduling', () => {
    const source = readFileSync(backgroundTaskFile, 'utf8');

    expect(source).toContain(
      'BGTaskScheduler.shared.cancel(taskRequestWithIdentifier: Self.taskIdentifier)',
    );
    expect(source).toContain('scheduleProcessingTask(after: 5 * 60)');
    expect(source).toContain('request.earliestBeginDate = Date(timeIntervalSinceNow: delay)');
  });

  it('refreshes the manifest when background resume skips an existing page', () => {
    const source = readFileSync(backgroundTaskFile, 'utf8');

    expect(source).toContain('if isNonEmptyFile(dest) {');
    expect(source).toContain(
      'writeManifest(galleryDir: galleryDir, exts: Array(exts.prefix(i + 1)))',
    );
  });

  it('keeps the BGProcessingTask identifier aligned across Swift and Info.plist', () => {
    const backgroundTask = readFileSync(backgroundTaskFile, 'utf8');
    const appDelegate = readFileSync(appDelegateFile, 'utf8');
    const plist = readFileSync(infoPlistFile, 'utf8');

    expect(backgroundTask).toContain('static let taskIdentifier = "com.hipago.app.download"');
    expect(appDelegate).toContain(
      'BGTaskScheduler.shared.register(forTaskWithIdentifier: DownloadBackgroundTask.taskIdentifier',
    );
    expect(plist).toContain('<key>BGTaskSchedulerPermittedIdentifiers</key>');
    expect(plist).toContain('<string>com.hipago.app.download</string>');
    expect(plist).toContain('<key>UIBackgroundModes</key>');
    expect(plist).toContain('<string>processing</string>');
  });

  it('keeps iOS background files in the same Directory.Data layout the reader uses', () => {
    const source = readFileSync(backgroundTaskFile, 'utf8');

    expect(source).toContain('private static let downloadsDirName = "downloads"');
    expect(source).toContain(
      'fileManager.urls(for: .documentDirectory, in: .userDomainMask).first',
    );
    expect(source).toContain(
      'return documents.appendingPathComponent(Self.downloadsDirName, isDirectory: true)',
    );
    expect(source).toContain('String(galleryId)');
    expect(source).toContain('String(format: "%04d.%@", index + 1, ext)');
  });

  it('keeps the iOS DownloadWorker plugin interface and handoff path aligned with TS', () => {
    const plugin = readFileSync(downloadWorkerPluginFile, 'utf8');

    expect(plugin).toContain('public let jsName = "DownloadWorker"');
    for (const method of ['writeWorkOrder', 'enqueue', 'cancel']) {
      expect(plugin).toContain(`CAPPluginMethod(name: "${method}"`);
      expect(plugin).toContain(`@objc func ${method}`);
    }
    expect(plugin).toContain('DownloadBackgroundTask.shared.handoffDir()');
    expect(plugin).toContain('DownloadBackgroundTask.shared.scheduleProcessingTask()');
    expect(plugin).toContain('DownloadBackgroundTask.shared.cancelPendingTask()');
    expect(plugin).toContain('work-order galleryId does not match filename');
  });
});
