'use client';

/**
 * Open-source licenses page.
 *
 * Statically imports the build-time `licenses.json` (generated by
 * scripts/build-licenses.mjs via the `prebuild` script) and renders two
 * filtered, grouped lists — JavaScript/npm deps and Rust/cargo deps.
 *
 * Filter is case-insensitive across name + license fields. Repo links open
 * in a new tab. The page itself has no network IO.
 */
import { useMemo, useState } from 'react';
import Link from 'next/link';
import { useT } from '@/lib/i18n/useT';
import licenses from '@/lib/licenses.json';

type Entry = {
  name: string;
  version: string;
  license: string;
  repository?: string;
};

function filterEntries(entries: Entry[], query: string): Entry[] {
  if (!query) return entries;
  const q = query.toLowerCase();
  return entries.filter(
    (e) => e.name.toLowerCase().includes(q) || e.license.toLowerCase().includes(q),
  );
}

function GroupSection({
  heading,
  entries,
  query,
}: {
  heading: string;
  entries: Entry[];
  query: string;
}) {
  const t = useT();
  const filtered = useMemo(() => filterEntries(entries, query), [entries, query]);
  if (entries.length === 0) return null;

  return (
    <section className="mb-8">
      <h2 className="mb-3 flex items-baseline gap-2 text-sm font-semibold tracking-wide text-zinc-700 uppercase dark:text-zinc-300">
        {heading}
        <span className="font-mono text-xs text-zinc-400 dark:text-zinc-500">{filtered.length}/{entries.length}</span>
      </h2>
      {filtered.length === 0 ? (
        <p className="rounded-lg border border-dashed border-zinc-200 px-4 py-6 text-center text-sm text-zinc-400 dark:border-zinc-800 dark:text-zinc-500">
          {t('licenses.empty')}
        </p>
      ) : (
        <ul className="divide-y divide-zinc-200 rounded-xl border border-zinc-200 bg-white dark:divide-zinc-800 dark:border-zinc-800 dark:bg-zinc-900">
          {filtered.map((e) => (
            <li key={`${e.name}@${e.version}`} className="flex items-baseline justify-between gap-4 px-4 py-2.5">
              <div className="min-w-0 flex-1">
                <p className="truncate text-sm font-medium text-zinc-900 dark:text-zinc-100">
                  {e.name}
                  <span className="ml-2 font-mono text-xs font-normal text-zinc-400 dark:text-zinc-500">v{e.version}</span>
                </p>
                <p className="truncate text-xs text-zinc-500 dark:text-zinc-400">{e.license}</p>
              </div>
              {e.repository && (
                <a
                  href={e.repository}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="shrink-0 text-xs text-blue-600 hover:underline dark:text-blue-400"
                >
                  {t('licenses.viewRepo')} ↗
                </a>
              )}
            </li>
          ))}
        </ul>
      )}
    </section>
  );
}

export default function LicensesPage() {
  const t = useT();
  const [query, setQuery] = useState('');
  const npm = (licenses.npm ?? []) as Entry[];
  const cargo = (licenses.cargo ?? []) as Entry[];

  return (
    <div className="mx-auto max-w-3xl">
      <div className="mb-6 flex items-center justify-between">
        <h1 className="text-2xl font-bold text-zinc-900 dark:text-zinc-100">{t('licenses.title')}</h1>
        <Link
          href="/settings"
          className="text-sm text-zinc-500 hover:text-zinc-700 dark:text-zinc-400 dark:hover:text-zinc-200"
        >
          ← {t('nav.settings')}
        </Link>
      </div>

      <input
        type="text"
        value={query}
        onChange={(e) => setQuery(e.target.value)}
        placeholder={t('licenses.search.placeholder')}
        className="mb-6 w-full rounded-md border border-zinc-300 bg-white px-3 py-2 text-sm text-zinc-900 focus:border-zinc-500 focus:outline-none focus:ring-1 focus:ring-zinc-500 dark:border-zinc-700 dark:bg-zinc-800 dark:text-zinc-100"
      />

      <GroupSection heading={t('licenses.npm.heading')} entries={npm} query={query} />
      <GroupSection heading={t('licenses.cargo.heading')} entries={cargo} query={query} />
    </div>
  );
}
